
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-translation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-translation
  template:
    metadata:
      labels:
        app: ai-translation
    spec:
      containers:
      - name: ai-translation
        imagePullPolicy: Always
        image: rubyroes/ai-translation:latest
        ports:
        - containerPort: 8005
        volumeMounts:
        # - name: db-storage
        #   mountPath: /code/db
        - name: main-py
          mountPath: /code/app/main.py
          subPath: main.py
        envFrom:
          - secretRef:
              name: openai-secret
      volumes:
      - name: main-py
        configMap:
          name: ai-bin

---
apiVersion: v1
kind: Service
metadata:
  name: ai-translation
spec:
  selector:
    app: ai-translation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005